apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.community.tanzu.vmware.com.1.9.1
spec:
  refName: cert-manager.community.tanzu.vmware.com
  version: 1.9.1
  releasedAt: 2021-10-29T12:00:00Z
  releaseNotes: "cert-manager 1.8.0 https://github.com/jetstack/cert-manager/releases/tag/v1.8.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/cert-manager@sha256:e321a8936343a3eb05676aa2cf5ba7b5a07a8867e94cab75bff68800fa6b0459
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  capacityRequirementsDescription: "Varies significantly based on number of Certificate objects"
  valuesSchema:
    openAPIv3:
      title: cert-manager.community.tanzu.vmware.com.1.9.1 values schema
      examples:
        - namespace: cert-manager
      properties:
        namespace:
          type: string
          description: The namespace in which to deploy cert-manager.
          default: cert-manager
